/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menus;

import control.View.Tela;

/**
 *
 * @author Aline
 */
public class ReservaAreaMenuView extends javax.swing.JPanel {

    /**
     * Creates new form ReservaAreaMenuView
     * @param permissao
     */
    public ReservaAreaMenuView(String permissao) {
        initComponents();
        if(permissao.equals("Morador") || permissao.equals("MoradorMestre") || permissao.equals("Porteiro")){
            inserirAreajButton.setVisible(false);
            consultarAreajButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReservarAreajButton = new javax.swing.JButton();
        ConsultarReservajButton = new javax.swing.JButton();
        inserirAreajButton = new javax.swing.JButton();
        consultarAreajButton = new javax.swing.JButton();

        ReservarAreajButton.setText("Reservar Área");
        ReservarAreajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarAreajButtonActionPerformed(evt);
            }
        });

        ConsultarReservajButton.setText("Consultar Reserva");
        ConsultarReservajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarReservajButtonActionPerformed(evt);
            }
        });

        inserirAreajButton.setText("Inserir Área");
        inserirAreajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirAreajButtonActionPerformed(evt);
            }
        });

        consultarAreajButton.setText("Consultar Área Cadastrada");
        consultarAreajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAreajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReservarAreajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(inserirAreajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultarAreajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsultarReservajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservarAreajButton)
                    .addComponent(ConsultarReservajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirAreajButton)
                    .addComponent(consultarAreajButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReservarAreajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarAreajButtonActionPerformed
        Tela.atualizaTela("ReservarArea");
    }//GEN-LAST:event_ReservarAreajButtonActionPerformed

    private void ConsultarReservajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarReservajButtonActionPerformed
        Tela.atualizaTela("ConsultarReserva");

    }//GEN-LAST:event_ConsultarReservajButtonActionPerformed

    private void inserirAreajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirAreajButtonActionPerformed
        Tela.atualizaTela("InserirArea");
    }//GEN-LAST:event_inserirAreajButtonActionPerformed

    private void consultarAreajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAreajButtonActionPerformed
        Tela.atualizaTela("ConsultarAreaCadastrada");
    }//GEN-LAST:event_consultarAreajButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarReservajButton;
    private javax.swing.JButton ReservarAreajButton;
    private javax.swing.JButton consultarAreajButton;
    private javax.swing.JButton inserirAreajButton;
    // End of variables declaration//GEN-END:variables
}
