/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paineis;

import control.domain.Control;
import control.domain.ControlFactory;
import control.exceptions.CpfInvalidoException;
import control.exceptions.DataInvalidaException;
import control.exceptions.TelefoneInvalidoException;
import control.exceptions.Validacoes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import model.domain.pessoas.Morador;
import model.domain.pessoas.Visitante;

/**
 *
 * @author Aline
 */
public class CadastroVisitanteView extends javax.swing.JPanel {

    /**
     * Creates new form CadastroVisitanteView
     */
    
    Control control;
    public CadastroVisitanteView(String permissao) {
        initComponents();
        
       this.nomeMoradorjComboBox.removeAllItems();
        control = ControlFactory.getMoradorControl();
        String array[]= control.pesquisar(new Morador());
        for(String a : array){
            this.nomeMoradorjComboBox.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomejLabel = new javax.swing.JLabel();
        CPFjLabel = new javax.swing.JLabel();
        NomejTextField = new javax.swing.JTextField();
        CPFjTextField = new javax.swing.JTextField();
        PrestadorServicojCheckBox = new javax.swing.JCheckBox();
        TelefonejLabel = new javax.swing.JLabel();
        TelefonejTextField = new javax.swing.JTextField();
        EntradajButton = new javax.swing.JButton();
        MoradorjLabel = new javax.swing.JLabel();
        NomeMoradorjLabel = new javax.swing.JLabel();
        VisitantejLabel = new javax.swing.JLabel();
        nomeMoradorjComboBox = new javax.swing.JComboBox<>();

        NomejLabel.setText("Nome:");

        CPFjLabel.setText("CPF:");

        PrestadorServicojCheckBox.setText("Prestador de Serviços");
        PrestadorServicojCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestadorServicojCheckBoxActionPerformed(evt);
            }
        });

        TelefonejLabel.setText("Telefone:");

        EntradajButton.setText("Registrar Entrada");
        EntradajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradajButtonActionPerformed(evt);
            }
        });

        MoradorjLabel.setText("Morador Responsável:");

        NomeMoradorjLabel.setText("Nome:");

        VisitantejLabel.setText("Visitante:");

        nomeMoradorjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EntradajButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(NomejLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NomejTextField))
                        .addComponent(PrestadorServicojCheckBox)
                        .addComponent(MoradorjLabel)
                        .addComponent(VisitantejLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CPFjLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CPFjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TelefonejLabel)
                            .addGap(10, 10, 10)
                            .addComponent(TelefonejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(NomeMoradorjLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomeMoradorjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(VisitantejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomejLabel)
                    .addComponent(NomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFjLabel)
                    .addComponent(CPFjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonejLabel)
                    .addComponent(TelefonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PrestadorServicojCheckBox)
                .addGap(18, 18, 18)
                .addComponent(MoradorjLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeMoradorjLabel)
                    .addComponent(nomeMoradorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EntradajButton)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PrestadorServicojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestadorServicojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrestadorServicojCheckBoxActionPerformed

    private void EntradajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradajButtonActionPerformed
        control = ControlFactory.getVisitanteControl();
        Visitante visitante= new Visitante();
        
        try{
            visitante.setPrestadorDeServico(this.PrestadorServicojCheckBox.isSelected());
            visitante.setNome(this.NomejTextField.getText());
            visitante.setCpf(Validacoes.isCPF(this.CPFjTextField.getText()));
            visitante.setTelefone(Validacoes.isTelefone(this.TelefonejTextField.getText()));
        }catch(TelefoneInvalidoException | CpfInvalidoException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        String data = sdf.format(new Date());
        Date date;
        try {
            date = Validacoes.isDataCompleta(data);
            visitante.setHoraDeEntrada(date);
        } catch (DataInvalidaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        Morador morador = new Morador();
        Control<Morador> moradorControl = ControlFactory.getMoradorControl();
        String[] partes = (this.nomeMoradorjComboBox.getItemAt(this.nomeMoradorjComboBox.getSelectedIndex())).split(":");
        morador.setCpf(partes[1].replaceAll("[^0-9]", ""));
        morador = moradorControl.bucarPorChave(morador);
        
        visitante.setMorador(morador);
        control.salvar(visitante);
        showMessageDialog(this, "Visitante cadastrado com sucesso!");
        
    }//GEN-LAST:event_EntradajButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFjLabel;
    private javax.swing.JTextField CPFjTextField;
    private javax.swing.JButton EntradajButton;
    private javax.swing.JLabel MoradorjLabel;
    private javax.swing.JLabel NomeMoradorjLabel;
    private javax.swing.JLabel NomejLabel;
    private javax.swing.JTextField NomejTextField;
    private javax.swing.JCheckBox PrestadorServicojCheckBox;
    private javax.swing.JLabel TelefonejLabel;
    private javax.swing.JTextField TelefonejTextField;
    private javax.swing.JLabel VisitantejLabel;
    private javax.swing.JComboBox<String> nomeMoradorjComboBox;
    // End of variables declaration//GEN-END:variables
}
