/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paineis;

import control.domain.impl.ControlImpl;
import control.domain.*;

/**
 *
 * @author Aline
 */
public class IncluirFinanceiroView extends javax.swing.JPanel {

    /**
     * Creates new form IncluirLancamentoView
     */
    public IncluirFinanceiroView(String permissao) {
        initComponents();
       
        RecDesjComboBox.removeAllItems();
        RecDesjComboBox.addItem("Receita");
        RecDesjComboBox.addItem("Despesa");
       
        TipoPgtojComboBox.removeAllItems();
        TipoPgtojComboBox.addItem("Boleto");
        TipoPgtojComboBox.addItem("Cheque");
        TipoPgtojComboBox.addItem("Depósito em Conta");
        TipoPgtojComboBox.addItem("Dinheiro");
        TipoPgtojComboBox.addItem("Outro");
        
        TipoLancjComboBox.removeAllItems();
        TipoLancjComboBox.addItem("Multas");
        TipoLancjComboBox.addItem("Taxa de condomínio");
        TipoLancjComboBox.addItem("Taxa de locação de área");
        TipoLancjComboBox.addItem("Pagamento à fornecedor");
        TipoLancjComboBox.addItem("Outro");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nomejLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        cpfjLabel = new javax.swing.JLabel();
        cpfjTextField = new javax.swing.JTextField();
        DtEmissaojLabel = new javax.swing.JLabel();
        DtEmissaojTextField = new javax.swing.JTextField();
        DtVencimentojLabel = new javax.swing.JLabel();
        DtVencimentojTextField = new javax.swing.JTextField();
        NroDocjLabel = new javax.swing.JLabel();
        NroDocjTextField = new javax.swing.JTextField();
        RecDesjLabel = new javax.swing.JLabel();
        RecDesjComboBox = new javax.swing.JComboBox<>();
        TipoPgtojLabel = new javax.swing.JLabel();
        TipoPgtojComboBox = new javax.swing.JComboBox<>();
        TipoLancjLabel = new javax.swing.JLabel();
        TipoLancjComboBox = new javax.swing.JComboBox<>();
        salvarjButton = new javax.swing.JButton();

        nomejLabel.setText("Nome:");

        cpfjLabel.setText("CPF/CNPJ:");

        DtEmissaojLabel.setText("Data emissão:");

        DtVencimentojLabel.setText("Data vencimento:");

        NroDocjLabel.setText("Nro. Documento:");

        RecDesjLabel.setText("Receita/Despesa:");

        RecDesjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RecDesjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecDesjComboBoxActionPerformed(evt);
            }
        });

        TipoPgtojLabel.setText("Tipo Pagamento:");

        TipoPgtojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoPgtojComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPgtojComboBoxActionPerformed(evt);
            }
        });

        TipoLancjLabel.setText("Tipo de Lançamento:");

        TipoLancjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoLancjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoLancjComboBoxActionPerformed(evt);
            }
        });

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomejTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TipoPgtojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoPgtojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TipoLancjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoLancjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvarjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RecDesjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecDesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DtEmissaojLabel)
                                .addGap(10, 10, 10)
                                .addComponent(DtEmissaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cpfjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfjTextField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DtVencimentojLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NroDocjLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DtVencimentojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NroDocjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecDesjLabel)
                    .addComponent(RecDesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfjLabel)
                    .addComponent(cpfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NroDocjLabel)
                    .addComponent(NroDocjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DtEmissaojLabel)
                    .addComponent(DtEmissaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DtVencimentojLabel)
                    .addComponent(DtVencimentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoPgtojLabel)
                    .addComponent(TipoPgtojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoLancjLabel)
                    .addComponent(TipoLancjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salvarjButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RecDesjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecDesjComboBoxActionPerformed
        
    }//GEN-LAST:event_RecDesjComboBoxActionPerformed

    private void TipoPgtojComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPgtojComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoPgtojComboBoxActionPerformed

    private void TipoLancjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoLancjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoLancjComboBoxActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        /*financeiroControl.salvarFinanceiro(this.NroDocjTextField.getText(), this.FornMorjTextField.getText(),
                (String) this.RecDesjComboBox.getSelectedItem(), (String) this.TipoPgtojComboBox.getSelectedItem(),
                (String) this.TipoLancjComboBox.getSelectedItem(), new java.sql.Date(new java.util.Date().getTime()),
                new java.sql.Date(new java.util.Date().getTime()),
                new java.sql.Date(new java.util.Date().getTime()));*/
    }//GEN-LAST:event_salvarjButtonActionPerformed

 private ControlImpl financeiroControl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DtEmissaojLabel;
    private javax.swing.JTextField DtEmissaojTextField;
    private javax.swing.JLabel DtVencimentojLabel;
    private javax.swing.JTextField DtVencimentojTextField;
    private javax.swing.JLabel NroDocjLabel;
    private javax.swing.JTextField NroDocjTextField;
    private javax.swing.JComboBox<String> RecDesjComboBox;
    private javax.swing.JLabel RecDesjLabel;
    private javax.swing.JComboBox<String> TipoLancjComboBox;
    private javax.swing.JLabel TipoLancjLabel;
    private javax.swing.JComboBox<String> TipoPgtojComboBox;
    private javax.swing.JLabel TipoPgtojLabel;
    private javax.swing.JLabel cpfjLabel;
    private javax.swing.JTextField cpfjTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton salvarjButton;
    // End of variables declaration//GEN-END:variables
}
