/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paineis;

/**
 *
 * @author Aline
 */
public class ReservarAreaView extends javax.swing.JPanel {

    /**
     * Creates new form ReservarAreaView
     */
    public ReservarAreaView(String permissao) {
        initComponents();
        
        areajComboBox.removeAllItems();
        areajComboBox.addItem("Quadra de futebol 1");
        areajComboBox.addItem("Quadra de futebol 2");
        areajComboBox.addItem("Quadra de futebol (areia)");
        areajComboBox.addItem("Quadra de vôlei");
        areajComboBox.addItem("Quadra de basquete");
        areajComboBox.addItem("Quadra de tênis");
        areajComboBox.addItem("Salão de festas");
        areajComboBox.addItem("Área gourmet");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areajLabel = new javax.swing.JLabel();
        areajComboBox = new javax.swing.JComboBox<>();
        horariojLabel = new javax.swing.JLabel();
        iniciojFormattedTextField = new javax.swing.JFormattedTextField();
        valorjLabel = new javax.swing.JLabel();
        valorjFormattedTextField = new javax.swing.JFormattedTextField();
        horariojLabel1 = new javax.swing.JLabel();
        fimjFormattedTextField = new javax.swing.JFormattedTextField();
        diaTodojCheckBox = new javax.swing.JCheckBox();
        solicitarjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cpfjTextField = new javax.swing.JTextField();

        areajLabel.setText("Escolha a área:");

        areajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        areajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areajComboBoxActionPerformed(evt);
            }
        });

        horariojLabel.setText("Início:");

        iniciojFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciojFormattedTextFieldActionPerformed(evt);
            }
        });

        valorjLabel.setText("Valor da reserva:");

        valorjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valorjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorjFormattedTextFieldActionPerformed(evt);
            }
        });
        valorjFormattedTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                valorjFormattedTextFieldPropertyChange(evt);
            }
        });

        horariojLabel1.setText("Fim:");

        diaTodojCheckBox.setText("Dia todo");
        diaTodojCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTodojCheckBoxActionPerformed(evt);
            }
        });

        solicitarjButton.setText("Solicitar");

        jLabel1.setText("CPF solicitante:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valorjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(solicitarjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(horariojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iniciojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(horariojLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(fimjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(diaTodojCheckBox)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areajLabel)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areajComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cpfjTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cpfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areajLabel)
                    .addComponent(areajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diaTodojCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horariojLabel)
                    .addComponent(iniciojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horariojLabel1)
                    .addComponent(fimjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorjLabel)
                    .addComponent(valorjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solicitarjButton))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valorjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorjFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorjFormattedTextFieldActionPerformed

    private void valorjFormattedTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_valorjFormattedTextFieldPropertyChange
        
    }//GEN-LAST:event_valorjFormattedTextFieldPropertyChange

    private void areajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areajComboBoxActionPerformed
        if(areajComboBox.getSelectedItem() == "Salão de festas" || areajComboBox.getSelectedItem() == "Área gourmet"){
            valorjFormattedTextField.setText("120,00");
            diaTodojCheckBox.setEnabled(true);
        }else{
            valorjFormattedTextField.setText("0,00");
            diaTodojCheckBox.setEnabled(false);
        }
    }//GEN-LAST:event_areajComboBoxActionPerformed

    private void diaTodojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTodojCheckBoxActionPerformed
        if(diaTodojCheckBox.isSelected()){
            iniciojFormattedTextField.setEnabled(false);
            fimjFormattedTextField.setEnabled(false);
        }else{
            iniciojFormattedTextField.setEnabled(true);
            fimjFormattedTextField.setEnabled(true);
        }
    }//GEN-LAST:event_diaTodojCheckBoxActionPerformed

    private void iniciojFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciojFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciojFormattedTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areajComboBox;
    private javax.swing.JLabel areajLabel;
    private javax.swing.JTextField cpfjTextField;
    private javax.swing.JCheckBox diaTodojCheckBox;
    private javax.swing.JFormattedTextField fimjFormattedTextField;
    private javax.swing.JLabel horariojLabel;
    private javax.swing.JLabel horariojLabel1;
    private javax.swing.JFormattedTextField iniciojFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton solicitarjButton;
    private javax.swing.JFormattedTextField valorjFormattedTextField;
    private javax.swing.JLabel valorjLabel;
    // End of variables declaration//GEN-END:variables
}
